export const modalProduct = document.querySelector('.modal_product');
export const catalogList = document.querySelector('.catalog__list');
export const modalProductTitle = document.querySelector('.modal-product__title');
export const modalProductImage = document.querySelector('.modal-product__image');
export const modalProductDescription = document.querySelector('.modal-product__description');
export const ingredientsList = document.querySelector('.ingredients__list');
export const ingredientsCalories = document.querySelector('.ingredients__calories');
export const modalProductPriceCount = document.querySelector('.modal-product__price-count');
export const navigationList = document.querySelector('.navigation__list');
export const navigationListItems = document.querySelectorAll('.navigation__button');
export const catalogTitle = document.querySelector('.catalog__title')
export const modalProductBtn = document.querySelector('.modal-product--btn')
export const countAmount = document.querySelector('.modal_product .count__amount')
export const orderCount = document.querySelector('.order__count')
export const orderList = document.querySelector('.order__list')
export const orderTotalAmount = document.querySelector('.order__total-amount')